version: "3.9"
   
services:
  web:
    build:
      context: .. 
      dockerfile: ./docker/nginx.dockerfile
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "3000:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80

